version: '3.1'

services:

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker

  redis:
    image: redis:5.0.6
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data