spring:
  datasource:
    url: jdbc:mysql://localhost:3306/samplerl
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

